Update update-bing-image.yml

diff --git a/.github/workflows/update-bing-image.yml b/.github/workflows/update-bing-image.yml
--- a/.github/workflows/update-bing-image.yml
+++ b/.github/workflows/update-bing-image.yml
@@ -25,34 +25,32 @@ jobs:
         run: |
           if [ -f image-of-the-day.jpg ]; then
             if cmp -s new-image-of-the-day.jpg image-of-the-day.jpg; then
-              echo "Images are the same. Skipping commit."
-              echo "commit_needed=false" >> $GITHUB_ENV
+              echo "Images are the same. No need to commit."
+              exit 1
             else
-              echo "Images are different. Commit is needed."
-              echo "commit_needed=true" >> $GITHUB_ENV
+              echo "Images are different. Proceeding to commit."
+              exit 0
             fi
           else
-            echo "No previous image found. Commit is needed."
-            echo "commit_needed=true" >> $GITHUB_ENV
+            echo "No previous image found. Proceeding to commit."
+            exit 0
+          fi
         id: compare_image
 
       - name: Commit and Push Changes
-        if: env.commit_needed == 'true' # Only commit if the previous step determined a commit is needed
+        if: steps.compare_image.conclusion == 'success' # Proceed if the previous step had exit code 0
         run: |
           mkdir -p iotd
           current_date=$(date +%F)
 
-          # Move the new image to replace the old one
           mv new-image-of-the-day.jpg image-of-the-day.jpg
 
-          # Copy the image to the iotd folder with the current date as the filename
           cp image-of-the-day.jpg iotd/$current_date.jpg
 
-          # Configure Git and commit the changes
           git config --local user.name "github-actions"
           git config --local user.email "github-actions@github.com"
-          git add image-of-the-day.jpg iotd/$current_date.jpg
-          git commit -m "Update image-of-the-day and archive $current_date"
+          git add image-of-the-day.jpg
+          git commit -m "Update image-of-the-day.jpg"
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
